import Head from 'next/head'
import Navigation from '../components/Navigation'
import React from 'react'

export interface AuthUser {
  data: {
    user: {
      id: string
      photo: string
      name: string
    }
  }
}

export interface LayoutProps {
  children: React.ReactNode
  data: {
    authUser: AuthUser
  }
}

export default function Layout({ children, data }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Open Space App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='app-container'>
        <header>
          <Navigation data={data} />
        </header>
        <main>{children}</main>
      </div>
    </>
  )
}
