import { IoEarthOutline } from 'react-icons/io5'
import RegisterInput from '../components/RegisterInput'
import Link from 'next/link'
import React from 'react'
import { GetServerSideProps } from 'next'
import Head from 'next/head'

export default function Register() {
  return (
    <>
      <Head>
        <title>Open Space App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='register-page'>
        <header className='register-page__hero'>
          <h1>
            <IoEarthOutline />
          </h1>
        </header>
        <article className='register-page__main'>
          <h2>Create your account</h2>
          <RegisterInput />

          <p>
            Already have an account? <Link href='/login'>Login</Link>
          </p>
        </article>
      </section>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { token } = context.req.cookies

  if (token) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: {},
  }
}
